export const AuthActionTypes = {
  LOGIN_USER_BY_MAIL_START: "LOGIN_USER_BY_MAIL_START",
  LOGIN_USER_BY_MAIL_SUCCESS: "LOGIN_USER_BY_MAIL_SUCCESS",
  LOGIN_USER_BY_MAIL_FAIL: "LOGIN_USER_BY_MAIL_FAIL",

  LOGIN_USER_BY_PHONE_START: "LOGIN_USER_BY_PHONE_START",
  LOGIN_USER_BY_PHONE_SUCCESS: "LOGIN_USER_BY_PHONE_SUCCESS",
  LOGIN_USER_BY_PHONE_FAIL: "LOGIN_USER_BY_PHONE_FAIL",

  REGISTER_USER_BY_MAIL_START: "REGISTER_USER_BY_MAIL_START",
  REGISTER_USER_BY_MAIL_SUCCESS: "REGISTER_USER_BY_MAIL_SUCCESS",
  REGISTER_USER_BY_MAIL_FAIL: "REGISTER_USER_BY_MAIL_FAIL",

  REGISTER_USER_BY_PHONE_START: "REGISTER_USER_BY_PHONE_START",
  REGISTER_USER_BY_PHONE_SUCCESS: "REGISTER_USER_BY_PHONE_SUCCESS",
  REGISTER_USER_BY_PHONE_FAIL: "REGISTER_USER_BY_PHONE_FAIL",

  UPDATE_USER_PROFILE_START: "UPDATE_USER_PROFILE_START",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAIL: "UPDATE_USER_PROFILE_FAIL",

  GET_USER_PROFILE_START: "GET_USER_PROFILE_START",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAIL: "GET_USER_PROFILE_FAIL",

  CHANGE_PASSWORD_START: "CHANGE_PASSWORD_START",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",

  REQUEST_MAIL_OTP_START: "REQUEST_MAIL_OTP_START",
  REQUEST_MAIL_OTP_SUCCESS: "REQUEST_MAIL_OTP_SUCCESS",
  REQUEST_MAIL_OTP_FAIL: "REQUEST_MAIL_OTP_FAIL",

  REQUEST_PHONE_NO_OTP_START: "REQUEST_PHONE_NO_OTP_START",
  REQUEST_PHONE_NO_OTP_SUCCESS: "REQUEST_PHONE_NO_OTP_SUCCESS",
  REQUEST_PHONE_NO_OTP_FAIL: "REQUEST_PHONE_NO_OTP_FAIL",

  VERIFY_MAIL_OTP_START: "VERIFY_MAIL_OTP_START",
  VERIFY_MAIL_OTP_SUCCESS: "VERIFY_MAIL_OTP_SUCCESS",
  VERIFY_MAIL_OTP_FAIL: "VERIFY_MAIL_OTP_FAIL",

  VERIFY_PHONE_NO_OTP_START: "VERIFY_PHONE_NO_OTP_START",
  VERIFY_PHONE_NO_OTP_SUCCESS: "VERIFY_PHONE_NO_OTP_SUCCESS",
  VERIFY_PHONE_NO_OTP_FAIL: "VERIFY_PHONE_NO_OTP_FAIL",

  AUTHENTICATE_USER: "AUTHENTICATE_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SHOW_OTP_MODAL: "SHOW_OTP_MODAL",
};

export const CustomerActionTypes = {
  ADD_NEW_SHIPPING_ADDRESS_START: "ADD_NEW_SHIPPING_ADDRESS_START",
  ADD_NEW_SHIPPING_ADDRESS_SUCCESS: "ADD_NEW_SHIPPING_ADDRESS_SUCCESS",
  ADD_NEW_SHIPPING_ADDRESS_FAIL: "ADD_NEW_SHIPPING_ADDRESS_FAIL",

  REMOVE_NEW_SHIPPING_ADDRESS_START: "REMOVE_NEW_SHIPPING_ADDRESS_START",
  REMOVE_NEW_SHIPPING_ADDRESS_SUCCESS: "REMOVE_NEW_SHIPPING_ADDRESS_SUCCESS",
  REMOVE_NEW_SHIPPING_ADDRESS_FAIL: "REMOVE_NEW_SHIPPING_ADDRESS_FAIL",

  UPDATE_SHPPING_ADDRESS_START: "UPDATE_SHPPING_ADDRESS_START",
  UPDATE_SHPPING_ADDRESS_SUCCESS: "UPDATE_SHPPING_ADDRESS_SUCCESS",
  UPDATE_SHPPING_ADDRESS_FAIL: "UPDATE_SHPPING_ADDRESS_FAIL",

  GET_SHPPING_ADDRESS_START: "GET_SHPPING_ADDRESS_START",
  GET_SHPPING_ADDRESS_SUCCESS: "GET_SHPPING_ADDRESS_SUCCESS",
  GET_SHPPING_ADDRESS_FAIL: "GET_SHPPING_ADDRESS_FAIL",

  GET_TOKEN_LISTING_START: "GET_TOKEN_LISTING_START",
  GET_TOKEN_LISTING_SUCCESS: "GET_TOKEN_LISTING_SUCCESS",
  GET_TOKEN_LISTING_FAIL: "GET_TOKEN_LISTING_FAIL",

  REDEEM_PROMO_CODE_START: "REDEEM_PROMO_CODE_START",
  REDEEM_PROMO_CODE_SUCCESS: "REDEEM_PROMO_CODE_SUCCESS",
  REDEEM_PROMO_CODE_FAIL: "REDEEM_PROMO_CODE_FAIL",

  SET_CUSTOM_ALERT: "SET_CUSTOM_ALERT",
};

export const ProductActionTypes = {
  GET_BANNER_IMAGES_START: "GET_BANNER_IMAGES_START",
  GET_BANNER_IMAGES_SUCCESS: "GET_BANNER_IMAGES_SUCCESS",
  GET_BANNER_IMAGES_FAIL: "GET_BANNER_IMAGES_FAIL",

  GET_PRIME_DEALS_START: "GET_PRIME_DEALS_START",
  GET_PRIME_DEALS_SUCCESS: "GET_PRIME_DEALS_SUCCESS",
  GET_PRIME_DEALS_FAIL: "GET_PRIME_DEALS_FAIL",

  GET_LIVE_ROMOTIONS_START: "GET_LIVE_ROMOTIONS_START",
  GET_LIVE_ROMOTIONS_SUCCESS: "GET_LIVE_ROMOTIONS_SUCCESS",
  GET_LIVE_ROMOTIONS_FAIL: "GET_LIVE_ROMOTIONS_FAIL",

  GET_PREMIUM_COUPONS_START: "GET_PREMIUM_COUPONS_START",
  GET_PREMIUM_COUPONS_SUCCESS: "GET_PREMIUM_COUPONS_SUCCESS",
  GET_PREMIUM_COUPONS_FAIL: "GET_PREMIUM_COUPONS_FAIL",

  GET_EXCLUSIVE_PRODUCTS_START: "GET_EXCLUSIVE_PRODUCTS_START",
  GET_EXCLUSIVE_PRODUCTS_SUCCESS: "GET_EXCLUSIVE_PRODUCTS_SUCCESS",
  GET_EXCLUSIVE_PRODUCTS_FAIL: "GET_EXCLUSIVE_PRODUCTS_FAIL",

  GET_SOLD_OUT_PRODUCTS_START: "GET_SOLD_OUT_PRODUCTS_START",
  GET_SOLD_OUT_PRODUCTS_SUCCESS: "GET_SOLD_OUT_PRODUCTS_SUCCESS",
  GET_SOLD_OUT_PRODUCTS_FAIL: "GET_SOLD_OUT_PRODUCTS_FAIL",

  GET_WINNERS_START: "GET_WINNERS_START",
  GET_WINNERS_SUCCESS: "GET_WINNERS_SUCCESS",
  GET_WINNERS_FAIL: "GET_WINNERS_FAIL",

  GET_TICKETS_START: "GET_TICKETS_START",
  GET_TICKETS_SUCCESS: "GET_TICKETS_SUCCESS",
  GET_TICKETS_FAIL: "GET_TICKETS_FAIL",

  ADD_TO_WISHLIST_START: "ADD_TO_WISHLIST_START",
  ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAIL: "ADD_TO_WISHLIST_FAIL",

  GET_WISHLIST_START: "GET_WISHLIST_START",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAIL: "GET_WISHLIST_FAIL",

  GET_RECENT_DRAWS_START: "GET_RECENT_DRAWS_START",
  GET_RECENT_DRAWS_SUCCESS: "GET_RECENT_DRAWS_SUCCESS",
  GET_RECENT_DRAWS_FAIL: "GET_RECENT_DRAWS_FAIL",

  GET_UPCOMMING_DRAWS_START: "GET_UPCOMMING_DRAWS_START",
  GET_UPCOMMING_DRAWS_SUCCESS: "GET_UPCOMMING_DRAWS_SUCCESS",
  GET_UPCOMMING_DRAWS_FAIL: "GET_UPCOMMING_DRAWS_FAIL",

  REDEEM_COUPON_START: "REDEEM_COUPON_START",
  REDEEM_COUPON_SUCCESS: "REDEEM_COUPON_SUCCESS",
  REDEEM_COUPON_FAIL: "REDEEM_COUPON_FAIL",

  REMOVE_FROM_WISHLIST_START: "REMOVE_FROM_WISHLIST_START",
  REMOVE_FROM_WISHLIST_SUCCESS: "REMOVE_FROM_WISHLIST_SUCCESS",
  REMOVE_FROM_WISHLIST_FAIL: "REMOVE_FROM_WISHLIST_FAIL",

  GET_ORDER_HISTORY_START: "GET_ORDER_HISTORY_START",
  GET_ORDER_HISTORY_SUCCESS: "GET_ORDER_HISTORY_SUCCESS",
  GET_ORDER_HISTORY_FAIL: "GET_ORDER_HISTORY_FAIL",

  BUY_PRODUCT_START: "BUY_PRODUCT_START",
  BUY_PRODUCT_SUCCESS: "BUY_PRODUCT_SUCCESS",
  BUY_PRODUCT_FAIL: "BUY_PRODUCT_FAIL",

  BUY_TOKENS_START: "BUY_TOKENS_START",
  BUY_TOKENS_SUCCESS: "BUY_TOKENS_SUCCESS",
  BUY_TOKENS_FAIL: "BUY_TOKENS_FAIL",

  REDEEM_PRIME_DEAL_START: "REDEEM_PRIME_DEAL_START",
  REDEEM_PRIME_DEAL_SUCCESS: "REDEEM_PRIME_DEAL_SUCCESS",
  REDEEM_PRIME_DEAL_FAIL: "REDEEM_PRIME_DEAL_FAIL",

  ADD_TO_CART: "ADD_TO_CART",
  IMPORT_CART_DATA: "IMPORT_CART_DATA",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_QUANTITY_FOR_CART_ITEM: "INCREMENT_QUANTITY_FOR_CART_ITEM",
  DECREMENT_QUANTITY_FOR_CART_ITEM: "DECREMENT_QUANTITY_FOR_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
};
